steps:
  - name: gcr.io/cloud-builders/bazel
    args: ["build", "//runs/graphql:docker"]
  - name: gcr.io/cloud-builders/bazel
    args: ["test", "//runs/graphql:test"]
  - name: gcr.io/cloud-builders/bazel
    entrypoint: "bash"
    args:
      - "-c"
      - |
        bazel build //runs/graphql:push --action_env=SHA=$SHORT_SHA --sandbox_debug
