steps:
  - name: gcr.io/cloud-builders/bazel
    args: ["build", "//runs/graphql:docker"]
  - name: gcr.io/cloud-builders/bazel
    args: ["test", "//runs/graphql:test"]
  - name: gcr.io/cloud-builders/bazel
    entrypoint: "bash"
    args:
      - "-c"
      - |
        bazel build //runs/graphql:tag --action_env=SHA=$SHORT_SHA
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/copenhagenjsdk/copenhagenjs.dk-graphql:$SHORT_SHA"]
